const config = {
  repository: {
    name: '',
    iconExtractPath: 'src/components/common/icons/svg',
    baseBranchName: 'main',
    owner: '',
  },
  commit: {
    message: 'feat: update icons',
    author: {
      name: '',
      email: '',
    },
  },
  pr: {
    title: 'Extract the icons from Figma',
    body: 'Please check the changed part!\n---\nThis Pull Request was generated by diffrag-figma-plugin.',
  },
};

export default config;
